### ISSUE TITLE
need option to prevent dropdown from closing when tapping/clicking on items in dropdown

### ISSUE THREAD

**Issue by nanowang** [Polymer/paper-dropdown#8]
Similar to [this](https://github.com/Polymer/core-dropdown/issues/12) issue in `core-dropdown`

Say I got an `input` in the `dropdown`, when I tap/click on the input, I probably dont want the dropdown to be closed. 

I've tried `e.stopPropagation()` to catch and stop the event but it doesnot work.

**Comment by diegohaz** [comment]
I got same issue.

**Comment by ebidel** [comment]
Repo: http://jsfiddle.net/n8q52gg5/

**Comment by morethanreal** [comment]
@nanowang Where are you listening to the `tap` event? I think if you listen to it on the `paper-dropdown` and do `e.stopPropagation()` there, it should work.

**Comment by morethanreal** [comment]
Fixed in Polymer/core-dropdown@53abf8d
